name: estimation
n_steps: 3.0
default_sbatch_opts:
  partition: epimodel
  mail-type: FAIL
  mail-user: user@emory.edu
steps:
- name: ~
  number: 1.0
  sbatch_opts:
    partition: epimodel
    mail-type: FAIL
    mail-user: user@emory.edu
    mem: 16G
    cpus-per-task: 4.0
    time: 120.0
- name: ~
  number: 2.0
  sbatch_opts:
    partition: epimodel
    mail-type: FAIL
    mail-user: user@emory.edu
    cpus-per-task: 10.0
    time: '24:00:00'
    mem: '0'
- name: ~
  number: 3.0
  sbatch_opts:
    partition: epimodel
    mail-type: END
    mail-user: user@emory.edu
    cpus-per-task: 10.0
    time: '04:00:00'
    mem-per-cpu: 4G
